### ISSUE TITLE
Link title is not saved

### ISSUE THREAD

**Issue by schaschko** [mdx-editor/editor#145]
Hi,

when using the `CreateLink` toolbar function, the title is not saved.

I was assuming adding a link to a text element would change the markdown from

`some text`

to

`[My Title](/some/path)`

I created a short animation of [the problem](https://gifyu.com/image/S8ppl).

Best regards

**Comment by petyosi** [comment]
Thank you. This is a bug in Lexical :(. I will try to fix it at some point.

**Comment by schaschko** [comment]
Another thing that could be related: when creating a link that spawns across more than one line of text, the full lines get highlighted on link creation, not just the part that was selected, which is at least confusing regarding UX. I'd say this is a UX problem, regarding function everything's fine, as link creation works as expected. Please see [this example](https://gifyu.com/image/S8H93).

**Comment by petyosi** [comment]
Opened a PR in Lexical on the title: https://github.com/facebook/lexical/pull/5191.

The link background is a funny one. Since the dialog moves the selection to the form, I "cheat" by adding a background element that matches the selection size, so that it is clear what's the boundary. However, this does not work with irregular shapes. 

Not sure what would be a simple straightforward fix for that. What do you think?

**Comment by petyosi** [comment]
Fixed with the newer lexical releases.
