### ISSUE TITLE
Can't update plugins list dynamically

### ISSUE THREAD

**Issue by dylanpyle** [mdx-editor/editor#165]
I'd like to hide/show the toolbar in certain cases, but updating the `plugins` list and re-rendering doesn't seem to achieve that.

If that's fixable behavior, or if there's another way to do so programmatically, I'd love any pointers.

My current usage is essentially:
```jsx
  const plugins: React.ComponentProps<typeof RealmPluginInitializer>['plugins'] = [
    headingsPlugin(),
    quotePlugin(),
    listsPlugin(),
    linkPlugin(),
    linkDialogPlugin(),
    jsxPlugin({ jsxComponentDescriptors }),
  ];

  if (showToolbar) {
    plugins.push(toolbarPlugin({
      toolbarContents: () => ( <>
        <CreateLink />
        <BoldItalicUnderlineToggles />
        <ListsToggle />
        <BlockTypeSelect />
      </>)
    }));
  }

  return (
    <MDXEditor
      className={className}
      contentEditableClassName={contentEditableClassName}
      ref={editorRef}
      markdown={markdown}
      onChange={onChange}
      readOnly={readOnly}
      plugins={plugins}
    />
  );
```

— but if my initial render includes `showToolbar`, then I turn it off, the toolbar remains.

**Comment by petyosi** [comment]
Dynamic plugin update is going to be extremely complicated. The plugins are responsible for certain markdown features, so doing that properly would mean re-processing the markdown with/without their features. 

I see two possible ways to achieve what you want:

- Rather than toggling the plugin, wrap the toolbar contents in a component and then toggle them from the inside using your preferred state management approach. 
- Pass a new `key` prop value to the editor when toggling the plugins. This will re-initialize the editor and its plugins.
