### ISSUE TITLE
Error Handling: Enhancement 

### ISSUE THREAD

**Issue by fredachang** [mdx-editor/editor#240]
Hi @petyosi, thanks for addressing the earlier issues on error handling and introducing some built-in handlers. However with the latest update in `1.13.4` our previous custom 'catch-all' has not stopped working as expected. Previously it would catch all unrecognised inputs and either display an empty paragraph node or converts the inputs into text, now it only catches certain characters and your built-in error comes up asking the user to correct source view.  

This is a little problematic because we don't intend to show `source-view` to the user unless they are an admin (because most of them aren't coders and won't be markdown literate). Is there a way to ensure rich-text view is ALWAYS available in case of an error? 

I am going to look further into how i can modify my catch all to still work for my needs, but I expect there will be some challenges because of conflicts the built-in error parser. Understand it's hard to make something that works for everyone, but the need to correct it in sourceview is really problematic for us. 

Thanks very much!

**Comment by petyosi** [comment]
The latest error handling still has lower precedence than the registered visitors, so a catch all plugin logic should work as expected. 

To show you what I mean, I [created this sandbox](https://codesandbox.io/p/sandbox/mdx-editor-catch-all-plugin-37d74k?file=/src/App.tsx:23,39). As you can see, the markdown uses an unknown construct (a heading), but the headings plugin is not there. However, the catch all plugin falls it back to a paragraph node. Since there's an eventual visitor that caught that node, the diff/source view error handling is not triggered. 

If I am missing something here, please fork the sandbox above and demonstrate the problem you experience.

**Comment by fredachang** [comment]
@petyosi thanks for creating this sandbox! I have reproduced the scenario mentioned earlier [here](https://codesandbox.io/p/sandbox/mdx-editor-catch-all-plugin-forked-qg8fdl?file=%2Fsrc%2FApp.tsx%3A46%2C31). The catch-all seems to pick up unsupported MD well but not something like ` <!-- -->`

**Comment by petyosi** [comment]
For what I've found out so far, the `<!-- -->` is actually causing a synta error when HTML parsing is turned on. It cannot be caught by a visitor (and somehow fallen back to something). More [details on that in the docs](https://mdxeditor.dev/editor/docs/error-handling#parse-errors-caused-by-html-like-formatting-eg-html-comments-or-links-surrounded-by-angle-brackets).

**Comment by fredachang** [comment]
hey @petyosi thanks for that. It works well now for most of our use cases if I add the `suppressHtmlProcessing` in addition to the catch all plug-in. Sorry the catch-all earlier was somehow able to convert html tags to paragraph out of the box so didn't think it could be the issue. 

Thanks again for your contribution :)
