### ISSUE TITLE
Bug - Link Dialogue State Management 

### ISSUE THREAD

**Issue by fredachang** [mdx-editor/editor#350]
Hello Petyo, 

Thank you for releasing version 2 - everything is working wonderfully except for one minor bug that may be unique to my application. I have tried to trouble shoot but am stuck - I was wondering if you are able to give me some pointers?

Issue: 
- When attaching a link for the first time, it works perfectly 
- once the link is saved to our database, and we want to update it again by clicking on save, we get the following error: 
![Screenshot 2024-02-05 at 11 02 26 am](https://github.com/mdx-editor/editor/assets/128881398/9bf5b98e-bf05-4352-b907-984f07102188)
- this error can be resolved if we give the link a 'title' on update
 
However the problem is we are hiding the title column with custom css as we don't need titles for links in our application.

I think the issue has got something to do with the title column being empty, but only on update. 

Unfortunately I've run your latest code base locally and cannot reproduce the error there, so this may be unique to scenarios where the link data is saved permanently to an external database and not just locally.

Let me know if you have any clues as to why this may be happening. 

Much appreciated, 
Freda

**Comment by jpreis** [comment]
We've also encountered this issue in our project. We have the exact same use case as @fredachang, we don't need titles for our links and would thus also hide the corresponding input.

The error @fredachang described can be reproduced on the MDXEditor [live demo](https://mdxeditor.dev/editor/demo):

- select the "Daring Fireball" link and click on the _edit_ icon
- try saving the link with an empty title field

![Bildschirmfoto 2024-04-03 um 16 55 28](https://github.com/mdx-editor/editor/assets/1215057/403c26ea-6d0b-4b4d-a756-de12d19f616f)

I think this might have to do with the initialization of the form state inside [LinkDialog.tsx](https://github.com/mdx-editor/editor/blob/main/src/plugins/link-dialog/LinkDialog.tsx)

```tsx
...
export function LinkEditForm({ url, title, onSubmit, onCancel, linkAutocompleteSuggestions }: LinkEditFormProps) {
  const {
    register,
    handleSubmit,
    control,
    setValue,
    reset: _
  } = useForm<LinkFormFields>({
    values: {
      url,
      title
    }
  })
```

I assume for some reason this gets initialized as `undefined` when the link was previously created with an empty title instead of empty string. I was able to work around this with the following adjustment:

```tsx
...
export function LinkEditForm({ url, title, onSubmit, onCancel, linkAutocompleteSuggestions }: LinkEditFormProps) {
  const {
    register,
    handleSubmit,
    control,
    setValue,
    reset: _
  } = useForm<LinkFormFields>({
    values: {
      url,
      title: title ?? ""
    }
  })
```

Regarding the described use case: It would be great to have an option to hide the title field via the plugin's API - currently, we have to use some hacky CSS to achieve this :)
