### ISSUE TITLE
Option to exclude underline

### ISSUE THREAD

**Issue by braincore** [mdx-editor/editor#44]
Unlike the other formatting options in `BoldItalicUnderlineToggles`, underline is implemented via HTML. In my case, I'm explicitly excluding HTML from markdown which requires excluding underline.

**Comment by petyosi** [comment]
I see your point for excluding html entirely, although this has some practical implications (for example, image sizes). 

The good thing is that the editor is fairly hackable in that sense, both in terms of behavior and toolbar items. [Here's an example](https://codesandbox.io/s/disable-underline-tx4npn?file=/src/App.tsx) that creates a custom B/I toggle and disables underline formatting with the keyboard shortcut.

Notice that if you plan on using images, you should pass `disableImageResize: true` to the image plugin. Otherwise, the users will be able to resize inserted images, and the editor will serialize those to `img` tags to preserve the explicit dimensions.

**Comment by roman-myshchyshyn** [comment]
@petyosi What is the point of reimplementing BoldItalicUnderlineToggles instead of providing one addtional option to already existing one? I will even say using `patch-package` is a better approach in this case.

**Comment by braincore** [comment]
Thanks! I finally put this to use.

Here's a version that works with v2.2.1:

```
const BoldItalicToggles = () => {
  const [currentFormat, iconComponentFor] = useCellValues(currentFormat$, iconComponentFor$);
  const applyFormat = usePublisher(applyFormat$);

  /* tslint:disable:no-bitwise */
  const boldIsOn = (currentFormat & IS_BOLD) !== 0;
  const italicIsOn = (currentFormat & IS_ITALIC) !== 0;
  /* tslint:enable:no-bitwise */

  const boldTitle = boldIsOn ? 'Remove bold' : 'Bold';
  const italicTitle = italicIsOn ? 'Remove italic' : 'Italic';

  return (
    <MultipleChoiceToggleGroup
      items={[
        {
          active: boldIsOn,
          contents: iconComponentFor('format_bold'),
          onChange: applyFormat.bind(null, 'bold'),
          title: boldTitle,
        },
        {
          active: italicIsOn,
          contents: iconComponentFor('format_italic'),
          onChange: applyFormat.bind(null, 'italic'),
          title: italicTitle,
        },
      ]}
    />
  );
};
```

**Comment by mledwards** [comment]
These are all the imports for the code snippet above

```
import {
  applyFormat$,
  currentFormat$,
  iconComponentFor$,
  IS_BOLD,
  IS_ITALIC,
  MultipleChoiceToggleGroup,
  useCellValues,
  usePublisher,
} from "@mdxeditor/editor";
```
