### ISSUE TITLE
Getting an error when using MDXEditor component in my react app

### ISSUE THREAD

**Issue by mohammadreza490** [mdx-editor/editor#8]
I'm importing the editor like this:
`import { MDXEditor } from '@mdxeditor/editor';`
and trying to use it in my component like this:
```
            <MDXEditor
              ref={mdEditor}
              onChange={(markdown) => {
                console.log(markdown);
              }}
            />
```
if I load the page with the component there, I get this error:
```
Error: Cannot find module 'path/to/file/node_modules/@lexical/react/LexicalComposer' imported from path/to/file/node_modules/@mdxeditor/editor/dist/index.js
Did you mean to import @lexical/react/LexicalComposer.js?
```
but if I comment it out, go to the page and uncomment it, then it works!!!

How can I fix the error?

Thanks

Version: `"0.6.1"`

**Comment by petyosi** [comment]
This seems to be a problem to your bundler setup. What are you using? Can you reproduce it in some isolation? I will take a look.

**Comment by mohammadreza490** [comment]
it basically doesn't allow me to import the `mdxeditor` package at all. I installed it with `npm install @mdxeditor/editor` but cannot import anything from it in my react pages (.tsx files). Please let me know what information you need and I'll provide them

**Comment by mohammadreza490** [comment]
we use Next for our react app

**Comment by petyosi** [comment]
[Here's a working example](https://github.com/mdx-editor/mdx-editor-in-next) of the editor embedded in a nextjs application. 

Notice that you need to use the dynamic approach, as the editor does not (nor has to) work with hydration.

If this still does not work in your environment, you can compare this with your setup (i.e. nextjs version, config settings, typescript,  etc.) and let me know what the culprit is.

**Comment by mohammadreza490** [comment]
Yes the dynamic approach works fine. I'll try to work more with the editor and re-open the issue if I still face problems. Thank you🙏🏼
